apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastucture
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/namespace"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client


